/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Cliente.Cliente;
import Cliente.ClienteDAO;
import Horarios.Horarios;
import Horarios.HorariosDAO;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Amanda de Oliveira
 */
public class FormAgendar extends javax.swing.JFrame {

    /**
     * Creates new form FormAgendar
     */
    public FormAgendar() {
        initComponents();
        
        ClienteDAO dao = new ClienteDAO();
        
        ArrayList<Cliente> listaClientes  = dao.ListaClientes();
        for (Cliente clientes : listaClientes) {
            jComboBoxClientes.addItem(clientes);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxClientes = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        inputDia = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        labelDesc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputDescricao = new javax.swing.JTextArea();
        buttonBuscarDia = new javax.swing.JButton();
        buttonCadastrarAgendamento = new javax.swing.JButton();
        buttonCancelarAgendamento = new javax.swing.JButton();
        inputHorario = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agendar Cliente");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("AGENDAMENTO");

        jLabel2.setText("Cliente:");

        jComboBoxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jComboBoxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClientesActionPerformed(evt);
            }
        });

        jLabel4.setText("Dia:");

        try {
            inputDia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Horário:");

        labelDesc.setText("Descrição:");
        labelDesc.setEnabled(false);

        inputDescricao.setColumns(20);
        inputDescricao.setRows(5);
        inputDescricao.setEnabled(false);
        jScrollPane1.setViewportView(inputDescricao);

        buttonBuscarDia.setText("Buscar Horário");
        buttonBuscarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarDiaActionPerformed(evt);
            }
        });

        buttonCadastrarAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon(1).png"))); // NOI18N
        buttonCadastrarAgendamento.setText("Cadastrar");
        buttonCadastrarAgendamento.setEnabled(false);
        buttonCadastrarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarAgendamentoActionPerformed(evt);
            }
        });

        buttonCancelarAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon(2).png"))); // NOI18N
        buttonCancelarAgendamento.setText("Cancelar");
        buttonCancelarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarAgendamentoActionPerformed(evt);
            }
        });

        try {
            inputHorario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(24, 24, 24)
                        .addComponent(inputDia, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonBuscarDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(buttonCancelarAgendamento)
                .addGap(55, 55, 55)
                .addComponent(buttonCadastrarAgendamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscarDia)
                    .addComponent(inputHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDesc)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCadastrarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(515, 352));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBuscarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarDiaActionPerformed
        ArrayList<Horarios> listaHorario = new ArrayList<Horarios>();
        HorariosDAO dao = new HorariosDAO();
        listaHorario = dao.buscaHorarios(inputDia.getText(), inputHorario.getText());
        
        /*
        if (inputDia.getText().equals("") && inputHorario.getText().equals("")){            
            listaHorario = dao.buscaHorarios(inputDia.getText(), inputHorario.getText());
            JOptionPane.showMessageDialog(null," Insira o horario!");
        }
        */        
        
        if(listaHorario.size()>0){
            JOptionPane.showMessageDialog(null, "Horário Indisponível!");
            inputDescricao.setEnabled(false);
            labelDesc.setEnabled(false);
            buttonCadastrarAgendamento.setEnabled(false);
            
        }else{
            JOptionPane.showMessageDialog(null, "Horário Disponível!");
            inputDescricao.setEnabled(true);
            labelDesc.setEnabled(true);
            buttonCadastrarAgendamento.setEnabled(true);
        }

    }//GEN-LAST:event_buttonBuscarDiaActionPerformed

    private void jComboBoxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClientesActionPerformed

    }//GEN-LAST:event_jComboBoxClientesActionPerformed

    private void buttonCadastrarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarAgendamentoActionPerformed
        HorariosDAO dao = new HorariosDAO();
        Cliente cliente = (Cliente) jComboBoxClientes.getSelectedItem();
        Horarios horario = new Horarios();       
        
        
        horario.setDescricao(inputDescricao.getText());
        horario.setIdCliente(cliente.getIdCliente());
        horario.setDia(inputDia.getText());
        horario.setHorario(inputHorario.getText());
        
        dao.inserir(horario);
        
        JOptionPane.showMessageDialog(null, "Cliente agendado com sucesso!");
        inputDescricao.setText("");
        inputDia.setText("");
        inputHorario.setText("");
        inputDescricao.setEnabled(false);
        labelDesc.setEnabled(false);
        buttonCadastrarAgendamento.setEnabled(false);
        
    }//GEN-LAST:event_buttonCadastrarAgendamentoActionPerformed

    private void buttonCancelarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarAgendamentoActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_buttonCancelarAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAgendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAgendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAgendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAgendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAgendar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscarDia;
    private javax.swing.JButton buttonCadastrarAgendamento;
    private javax.swing.JButton buttonCancelarAgendamento;
    private javax.swing.JTextArea inputDescricao;
    private javax.swing.JFormattedTextField inputDia;
    private javax.swing.JFormattedTextField inputHorario;
    private javax.swing.JComboBox<Object> jComboBoxClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDesc;
    // End of variables declaration//GEN-END:variables
}
