/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Preco.Preco;
import Preco.PrecoDAO;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amanda de Oliveira
 */
public class TelaPreco extends javax.swing.JFrame {

    static JTable table;
    String[] columns = {"Id", "Corte", "Preço"}; 
    String from;
    JComboBox c1;
    
    public TelaPreco() {
        initComponents();
    }
    
    public void readJTable(){        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputpreco = new javax.swing.JTextField();
        inputCadastrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTPrecos = new javax.swing.JTable();
        buttonMostrarPreco = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabela de Preços");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 80, 40, 14);
        getContentPane().add(inputnome);
        inputnome.setBounds(80, 70, 320, 30);

        jLabel2.setText("Preço:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 130, 40, 14);
        getContentPane().add(inputpreco);
        inputpreco.setBounds(80, 120, 122, 30);

        inputCadastrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        inputCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dollar.png"))); // NOI18N
        inputCadastrar.setText("Cadastrar");
        inputCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(inputCadastrar);
        inputCadastrar.setBounds(283, 110, 117, 40);

        jTPrecos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTPrecos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço"
            }
        ));
        jScrollPane2.setViewportView(jTPrecos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 250, 370, 201);

        buttonMostrarPreco.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buttonMostrarPreco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sort-down.png"))); // NOI18N
        buttonMostrarPreco.setText("Listar Preços");
        buttonMostrarPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMostrarPreco);
        buttonMostrarPreco.setBounds(30, 200, 140, 40);

        buttonVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buttonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/left-arrow.png"))); // NOI18N
        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonVoltar);
        buttonVoltar.setBounds(190, 200, 95, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("PREÇOS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 30, 90, 22);

        setSize(new java.awt.Dimension(448, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCadastrarActionPerformed
        PrecoDAO dao = new PrecoDAO();
        Preco preco = new Preco();
        preco.setNome(inputnome.getText());
        preco.setPreco(inputpreco.getText());
        dao.inserir(preco);
        
        DefaultTableModel modelPreco = (DefaultTableModel) jTPrecos.getModel();
        
        Object[] dados = {preco.getNome(), preco.getPreco()};
        modelPreco.addRow(dados);
        inputnome.setText("");
        inputpreco.setText("");
    }//GEN-LAST:event_inputCadastrarActionPerformed

    private void buttonMostrarPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarPrecoActionPerformed
       
        PrecoDAO dao = new PrecoDAO();
        
        ArrayList<Preco> listaPreco = dao.ListaPreco();
        DefaultTableModel modelPreco = (DefaultTableModel) jTPrecos.getModel();
        
        for (Preco preco1 : listaPreco) {
            Object[] dados = {preco1.getNome(), preco1.getPreco()};
            modelPreco.addRow(dados);
        }
        
        buttonMostrarPreco.setEnabled(false);
       
    }//GEN-LAST:event_buttonMostrarPrecoActionPerformed

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonVoltarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
               
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPreco().setVisible(true);
            }
        });
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMostrarPreco;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JButton inputCadastrar;
    private javax.swing.JTextField inputnome;
    private javax.swing.JTextField inputpreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTPrecos;
    // End of variables declaration//GEN-END:variables
}
